# * EEG
Send_EEG_trigg: True
Actiview_reminder: True

# * view parameters
# Screen_color: "grey"
Screen_color: "#877c76"
Text_size: 0.04
Text_font: "Arial"
Text_color: "black"

Break_every_n_trials: 12
Repeats:
  Congruent: 1
  Incongruent_McGurk: 1
  Incongruent_Phe: 1
  Incongruent_Vis: 1

# Stimulus sizes 
Video_height: 0.57  # in screen height

# Timings
Pre_video_duration: 1.0

Greeting_texts:
  - |
    Witaj w naszym badaniu!

    (wciśnij spację aby kontynuować)
  - |
    Za chwilę weźmiesz udział w eksperymencie dotyczącym 
    percepcji i rozumienia dźwięków mowy.

    Podczas eksperymentu będziemy pokazywać Ci filmy z osobą
    wypowiadającą różne sylaby – po jednej sylabie na raz.

    (wciśnij spację aby kontynuować)
  - |
    Prosimy, abyś podczas oglądania filmów skupił/a swoją
    uwagę wyłącznie na osobıe mówiącej.

    Obejrzysz łącznie TODO filmów.
    Całe badanie potrwa około TODO minut.

    (wciśnij spację aby kontynuować)
  - |
    Wciśnij spację aby rozpocząć badanie.

Break_text: |
    Przerwa!

    (wciśnij spację aby kontynuować)

End_text: |
    Gratulacje! Badanie zakończyło się. 
    Zaczekaj na osobę przeprowadzającą eksperyment.

    (wciśnij spację aby zakończyć badanie)



