# * EEG
Send_EEG_trigg: False
Actiview_reminder: True

# * view parameters
# Screen_color: "grey"
Screen_color: "#877c76"
Text_size: 0.04
Text_font: "Arial"
Text_color: "black"

Break_every_n_trials: 12
# Repeats: 2  # How many times each video is shown
Repeats:
  Congruent: 2
  Incongruent_McGurk: 2
  Incongruent_Phe: 4
  Incongruent_Vis: 4

# # Stimulus sizes 
# Screen_distance: 50  # cm
# Screen_height: 30  # cm
# In degrees of visual angle
#
# Stimulus sizes 
Video_height: 0.5  # in screen height

# Timings
Pre_video_duration: 1.0

Greeting_texts:
  - |
    Witaj w naszym badaniu!

    (wciśnij spację aby kontynuować)
  - |
    TODO instrukcje skibidi

    (wciśnij spację aby kontynuować)

Break_text: |
    Przerwa!

    (wciśnij spację aby kontynuować)

End_text: |
    Gratulacje! Badanie zakończyło się. Zaczekaj na osobę przeprowadzającą eksperyment.

    (wciśnij spację aby zakończyć badanie)



