# * EEG
Send_EEG_trigg: False
Actiview_reminder: True

# * view parameters
# Screen_color: "grey"
Screen_color: "#877c76"
Text_size: 0.04
Text_font: "Arial"
Text_color: "black"

# Stimulus sizes 
# Screen_distance: 50  # cm
# Screen_height: 30  # cm
# In degrees of visual angle
#
# Stimulus sizes 
Video_height: 0.5  # in screen height

# Timings
Pre_video_duration: 1.0

Greeting_texts:
  - |
    Witaj w naszym badaniu!

    (wciśnij spację aby kontynuować)
  - |
    Twoim zadaniem będzie szacowanie upływu jednej sekundy.
    Staraj się wcisnąć spację dokładnie sekundę po pojawieniu się gwiazdki na ekranie.

    (wciśnij spację aby kontynuować)
  - |
    Teraz przejdziemy przez kilka przykładów.
    Po każdej próbie dostaniesz informację,
    czy byłeś/byłaś wystarczająca blisko sekundy.

    (wciśnij spację aby kontynuować)

Wait_text: |
    wciśnij spację aby kontynuować

End_text: |
    Gratulacje! Badanie zakończyło się. Zaczekaj na osobę przeprowadzającą eksperyment.

    (wciśnij spację aby zakończyć badanie)



